#!/usr/bin/env python3
"""
invariant_generator.py — Generate Foundry invariant_* tests from invariant statements.

Used in /deephunt J2 (Invariant Break) to translate human-described invariants
into runnable Foundry stateful invariant tests.

Usage:
  python3 invariant_generator.py --invariants sessions/X/invariants.md --output sessions/X/invariant_tests/
  python3 invariant_generator.py --invariant "totalShares == sum(balances)" --target Vault --output ...

The generated tests are SCAFFOLDING. User fills in:
- targetContract (which contract to fuzz)
- Setup function (state initialization)
- Actor wrappers (which functions to fuzz call from)

Output: Foundry-ready .t.sol files
"""

import argparse
import json
import re
from pathlib import Path

TEMPLATE = """// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Test.sol";
import "forge-std/StdInvariant.sol";

// AUTO-GENERATED INVARIANT TEST
// Invariant: {invariant_description}
// Source: {source_location}
// Generated by: invariant_generator.py

interface ITarget {{
    // TODO: add target contract interface methods here
}}

contract Handler {{
    ITarget public target;

    // TODO: add actors / users array
    address[] public actors;

    // TODO: track ghost state for invariant checking
    // mapping(address => uint256) public ghostBalances;
    // uint256 public ghostTotalSupply;

    constructor(ITarget _target) {{
        target = _target;
        actors.push(makeAddr("alice"));
        actors.push(makeAddr("bob"));
        actors.push(makeAddr("carol"));
    }}

    function makeAddr(string memory name) internal pure returns (address) {{
        return address(uint160(uint256(keccak256(abi.encodePacked(name)))));
    }}

    // TODO: add wrapped action functions that the fuzzer will call
    // function deposit(uint256 amount, uint256 actorSeed) public {{
    //     amount = bound(amount, 1, 1e30);
    //     address actor = actors[actorSeed % actors.length];
    //     vm.prank(actor);
    //     target.deposit(amount);
    //     // Update ghost state
    // }}
}}

contract InvariantTest_{test_name} is StdInvariant, Test {{
    ITarget public target;
    Handler public handler;

    function setUp() public {{
        // TODO: deploy target contract
        // target = ITarget(deployTargetWithDefaults());

        handler = new Handler(target);
        targetContract(address(handler));
    }}

    /// Invariant: {invariant_description}
    function invariant_{invariant_id}() public view {{
        // TODO: implement invariant check
        // Example:
        // uint256 totalSupply = target.totalSupply();
        // uint256 sumOfBalances;
        // for (uint i; i < handler.actorsLength(); i++) {{
        //     sumOfBalances += target.balanceOf(handler.actors(i));
        // }}
        // assertEq(totalSupply, sumOfBalances, "{invariant_description}");

        assertTrue(true, "PLACEHOLDER — implement invariant check");
    }}
}}
"""


def slugify(text: str, max_len: int = 30) -> str:
    """Convert invariant text to a valid Solidity identifier."""
    slug = re.sub(r"[^a-zA-Z0-9]+", "_", text)
    slug = re.sub(r"_+", "_", slug).strip("_")
    return slug[:max_len] if slug else "invariant"


def generate_test(
    invariant_description: str,
    test_name: str,
    invariant_id: str = None,
    source_location: str = "manual input",
) -> str:
    """Generate a Foundry test file content for an invariant."""
    if not invariant_id:
        invariant_id = slugify(invariant_description)
    return TEMPLATE.format(
        invariant_description=invariant_description,
        source_location=source_location,
        test_name=test_name,
        invariant_id=invariant_id,
    )


def _parse_model_table(content: str) -> list[dict]:
    """Parse the T13 `system_model.md` `I-NN` table (12 columns).

    Header (system_model_template.md): | ID | Formula | check: | Class | Source |
    component: | pred: | Status | file:line | tests | crowd-heat | lib |
    Rows start with `| I-01 | ...`. Empty-formula template rows are skipped.
    Fuzzing priority — statuses ABSENT / ENFORCED-PARTIAL / SUBSTITUTED (the defect is there), but the skeleton is
    generated for EVERY filled-in `I-NN`; the "not checkable by reading" filter is the agent's judgment, not the parser's.
    """
    invs = []
    for line in content.splitlines():
        s = line.strip()
        m = re.match(r"^\|\s*I-?(\d+)\s*\|(.*)$", s)
        if not m:
            continue
        cols = [c.strip().strip("`").strip() for c in s.split("|")[1:-1]]
        if len(cols) < 2 or not cols[1]:      # empty formula = unfilled template row
            continue
        status = cols[7] if len(cols) > 7 else ""
        loc = cols[8] if len(cols) > 8 and cols[8] else "unknown"
        invs.append({
            "id": f"I{m.group(1)}",            # I-01 → I01 (valid solidity identifier)
            "description": cols[1],
            "location": loc,
            "classification": "model_invariant",
            "broader_class": "independent_model_first",
            "status": status,
        })
    return invs


def parse_invariants_md(md_path: Path) -> list[dict]:
    """Parse invariants from either the T13 model table OR the legacy list format.

    Format A (T13, priority): table `I-NN` from `system_model.md` — `| I-01 | formula | ... |`.
    Format B (legacy): `## I<N>: <text>` + `- Location: file:line` (deep/invariants.md).
    """
    if not md_path.exists():
        return []
    content = md_path.read_text(encoding="utf-8", errors="ignore")
    table = _parse_model_table(content)   # T13 model table first
    if table:
        return table
    invariants = []
    # Match h2 headers like "## I1: ..."
    pattern = re.compile(r"##\s+I(\d+):\s*(.+?)(?=\n##|\Z)", re.DOTALL)
    for m in pattern.finditer(content):
        idx = m.group(1)
        body = m.group(2).strip()
        # First line = description
        first_line = body.split("\n", 1)[0].strip()
        location_match = re.search(r"Location:\s*[`']?([^`'\n]+)[`']?", body)
        # Classification: invariants from comments (Alchemix-style) = known class; novel discoveries = novel
        # All invariants extracted here came from author's own comments → known_class (we are formalizing)
        invariants.append({
            "id": f"I{idx}",
            "description": first_line,
            "location": location_match.group(1) if location_match else "unknown",
            "classification": "known_class",
            "broader_class": "author_declared_invariant",
        })
    return invariants


def main():
    p = argparse.ArgumentParser(description="Generate Foundry invariant tests")
    p.add_argument("--invariants", help="Path to invariants.md")
    p.add_argument("--invariant", help="Single invariant text")
    p.add_argument("--target", default="Target", help="Target contract name for test class")
    p.add_argument("--output", required=True, help="Output directory")
    args = p.parse_args()

    output_dir = Path(args.output)
    output_dir.mkdir(parents=True, exist_ok=True)

    if args.invariants:
        invariants = parse_invariants_md(Path(args.invariants))
        if not invariants:
            print(f"WARN: no invariants parsed from {args.invariants}")
            return 1
        for inv in invariants:
            test_name = f"{args.target}_{inv['id']}"
            content = generate_test(
                inv["description"],
                test_name,
                inv["id"].lower(),
                inv["location"],
            )
            out_file = output_dir / f"{test_name}.t.sol"
            out_file.write_text(content, encoding="utf-8")
            print(f"[+] {out_file.name}")
    elif args.invariant:
        test_name = f"{args.target}_invariant"
        content = generate_test(args.invariant, test_name, source_location="--invariant CLI arg")
        out_file = output_dir / f"{test_name}.t.sol"
        out_file.write_text(content, encoding="utf-8")
        print(f"[+] {out_file.name}")
    else:
        print("ERROR: provide --invariant or --invariants")
        return 1

    print(f"\n[+] Generated tests in {output_dir}")
    print("[!] Edit each test to:")
    print("    1. Implement ITarget interface for your contract")
    print("    2. Deploy target in setUp()")
    print("    3. Add Handler action wrappers")
    print("    4. Implement the actual invariant check")
    print("    5. Run: forge test --match-test invariant -vvv")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
